site_name: TESS Case Studies
nav:
    - Home : README.md
    - Case Studies:
      - notebooks/pixel-level-detrending.ipynb

theme:
  name: "material"
  icon:
    logo: material/pencil
  palette:
    scheme: default
    primary: blue grey
    accent: black
  features:
      - navigation.tabs
      - navigation.tabs.sticky
repo_url: https://github.com/tessgi/tess-case-studies
plugins:
  - include-markdown
  - search
  - mkdocs-jupyter:
      execute: False
  - social
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NASA_TESS
      name: TESS on twitter
    - icon: fontawesome/brands/github
      link: https://github.com/tessgi
      name: TESS GI on GitHub
    - icon: fontawesome/solid/paper-plane
      link: mailto:tesshelp@bigbang.gsfc.nasa.gov
      name: Email us!
